version: "3.9"

services:

db:
 build: 
  context: ./requierments/mariadb
 conatainer_name: mariadb
 restart: always
 env_files: .env
 volumes:
  - 
  -
 networks:
  - 42networks

wordpress:
 build: 
  context: ./requierments/wordpress
  args: tpaquier.42.fr
 container_name: wordpress
 depends_on:
  - db
 restart: always
 env_files: .env
 volumes:
  - wordpress:/var/www/html
  - 
 networks:
  - 42networks

web:
 build: 
  context: ./requierments/nginx
  args: tpaquier.42.fr
 container_name: nginx
 depends_on:
  - wordpress
 restart: always
 env_files: .env
 volumes:
  - wordpress:/var/www/html
 networks:
  - 42networks

networks:
 42networks:

volume:

 db:
  driver:
  driver_opts:
   type:
   O:
   device:

 wordpress:
  driver:
  driver_opts:
   type:
   O:
   device: