version: "3.9"

services:
  
  mariadb:
    build: 
      context: ./requirements/mariadb
    container_name: mariadb
    restart: on-failure:10
    env_file: .env
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - 42networks
  
  wordpress:
    build: 
      context: ./requirements/wordpress
      args:
        DOMAIN_NAME : ${DOMAIN_NAME}
    container_name: wordpress
    depends_on:
      mariadb:
        condition: service_started
    restart: on-failure:10
    env_file: .env
    volumes:
      - wpdata:/var/www/html
    networks:
      - 42networks

  nginx:
    build: 
      context: ./requirements/nginx
      args:
        DOMAIN_NAME: ${DOMAIN_NAME}
    container_name: nginx
    depends_on:
      wordpress:
        condition: service_started
    env_file: .env
    ports:
      - 443:443
    restart: on-failure:10
    volumes:
      - wpdata:/var/www/html
    networks:
      - 42networks
  
networks:
  42networks: 
  
volumes:
  dbdata:
    driver: local
    driver_opts:
      type: "none"
      o: "bind"
      device: "/home/tpaquier/data/data"
  wpdata:
    driver: local
    driver_opts:
      type: "none"
      o: "bind"
      device: "/home/tpaquier/data/wordpress"