version: "3.9"

services:

db:
 build: 
  context: ./requierments/mariadb
 conatainer_name: mariadb
 restart: on-failure
 environement:
  MARIADB_ROOT_PASSWORD: ${MDB_ROOT_PASSWORD}
  MARIADB_USER: ${MDB_USER}
  MARIADB_PASSWORD: ${MDB_PASSWORD}
  MARIADB_DATABASE: ${MDB_DATABASE}
 env_files: .env
 volumes:
  - dbdata:/var/www/html
 ports:
   - "3306:3306"
 networks:
  - 42networks

web:
 build: 
  context: ./requierments/nginx
 container_name: nginx
 depends_on:
  - wordpress.
 environement:
  - NGINX_HOST=${DOMAIN_NAME}
 restart: on-failure
 env_files: .env
 volumes:
  - wordpress:/var/www/html
 networks:
  - 42networks

wordpress:
 build: 
  context: ./requierments/wordpress
 container_name: wordpress
 depends_on:
  - db
 restart: on-failure
 environement:
  WORDPRESS_DB_HOST: db:3306
  WORDPRESS_DB_PASSWORD: ${MDB_PASSWORD}
  WORDPRESS_DB_USER: ${MDB_USER}
  WORDPRESS_DB_NAME: ${MDB_DATABASE}
 env_files: .env
 volumes:
  - wordpress:/var/www/html
 networks:
  - 42networks

networks:
 42networks:

volume:

 dbdata:
  driver: local
  driver_opts:
   type: none
   o: "bind"
   device: "/home/tpaquier/data"

 wordpress:
  driver: local
  driver_opts:
   type: none
   o: "bind"
   device: "/home/wordpress"