version: "3.9"
#https://www.data-transitionnumerique.com/docker-volume/
services:
	db:
		image: mariadb
		restart: always
		ports:
		 - "3306:3306"
		environment:
		MARIADB_ROOT_PASSWORD: #inserer le password ici
		networks:
		 - 42networks

	wordpress:
    image: wordpress
    restart: always
    ports:
      - "9000:9000"
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: exampleuser
      WORDPRESS_DB_PASSWORD: examplepass
      WORDPRESS_DB_NAME: exampledb
    volumes:
      - wordpress:/var/www/html
		networks:
		 - 42networks

	web:
		image: nginx
		restart: always
		volumes:
		- ./templates:/etc/nginx/templates
		ports:
		- "443:443"
		environment:
		- NGINX_HOST=foobar.com
		- NGINX_PORT=80
		networks:
		 - 42networks

networks:
	42networks:

volume:
	db:
	wordpress: