SET PASSWORD FOR 'root'@'localhost' =PASSWORD(${MDB_ROOT_PASSWORD});
CREATE DATABASE IF NOT EXIST $MDB_DATABASE;
CREATE USER ${MDB_USER}@'localhost' IDENTIFIED BY ${MDB_PASSWORD};
GRANT ALL PRIVILEGES ON ${MDB_DATABASE}.* TO ${MDB_USER}@'localhost';

FLUSH PRIVILEGES;