DROP DATABASE IF EXISTS test;
DELETE FROM mysql.db WHERE Db='test';
DELETE FROM mysql.user WHERE User='';
DELETE FROM mysql.user WHERE User='root' AND Host NOT IN ('localhost', '127.0.0.1', '::1');

SET PASSWORD FOR 'root'@'localhost' =PASSWORD(${MDB_ROOT_PASSWORD});
CREATE DATABASE IF NOT EXIST $MDB_DATABASE;
CREATE USER ${MDB_USER}@'localhost' IDENTIFIED BY ${MDB_PASSWORD};
GRANT ALL PRIVILEGES ON ${MDB_DATABASE}.* TO ${MDB_USER}@'localhost';

FLUSH PRIVILEGES;