DROP DATABASE IF EXISTS test;
DELETE FROM mysql.db WHERE Db='test';
DELETE FROM mysql.user WHERE User='';
DELETE FROM mysql.user WHERE User='root' AND Host NOT IN ('localhost', '127.0.0.1', '::1');

SET PASSWORD FOR 'root'@'localhost' = PASSWORD('$MDB_ROOT_PASSWORD');

CREATE DATABASE IF NOT EXISTS $MDB_DATABASE;
CREATE USER IF NOT EXISTS '$MDB_USER'@'%' IDENTIFIED BY '$MDB_PASSWORD';
GRANT ALL PRIVILEGES ON $MDB_DATABASE.* TO $MDB_USER@'%';

FLUSH PRIVILEGES;